### ISSUE TITLE
Different Profile Error

### ISSUE THREAD

**Issue by oitear** [SkyCryptWebsite/SkyCrypt#1889] opened 2023-02-28 23:00 UTC
It says I am on a completely different profile than I actually am, and has done so for days. (To add, the profile it says I'm on doesn't even exist. I only have 3, not 4, those 3 are Tomato, Orange, and Watermelon)

(https://sky.shiiyu.moe/stats/oitear/Pineapple)

I don't think it matters but I've been on my private island with Superior armor and Enderman Pet

I was expecting the proper profile to be shown as the one I am playing on.

![profiles](https://user-images.githubusercontent.com/126625595/222001339-5ac484cf-350f-41db-9577-ed209d6567a7.png)
![Screenshot (3)](https://user-images.githubusercontent.com/126625595/222001387-6643519e-7cd7-48c4-b68d-74f681614b12.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Home
- Browser: Chrome
- Version: 22H2

**Comment by DuckySoLucky** [comment] 2023-03-16 13:35
Heya, thank you for reporting this issue. Unfortunately, I'm not able to reproduce the bug with the information provided. Could you provide more information?

**Comment by Kathund** [comment] 2023-03-27 00:53
@oitear is the error your talking about with the extra profile called **Pineapple**? Because if so i dont think we can fix it because of how the hypixel api gives up data

**Comment by DespicableGoose** [comment] 2023-08-06 22:35
I don't think this was an error, as the symbol before the name of the profile indicates it was a Bingo profile. Bingo profiles do not appear in the profile management menu, which is likely why you believed the profile didn't exist. As for the order of profiles, that might be a bug, but it's more likely something Hypixel side rather than SkyCrypt side. I think this issue can probably be closed.

**Comment by DuckySoLucky** [comment] 2023-08-06 22:37
> I don't think this was an error, as the symbol before the name of the profile indicates it was a Bingo profile. Bingo profiles do not appear in the profile management menu, which is likely why you believed the profile didn't exist. As for the order of profiles, that might be a bug, but it's more likely something Hypixel side rather than SkyCrypt side. I think this issue can probably be closed.

yeah, we talked about this on discord he misunderstood something

@metalcupcake5 close this too :CatYes:

**Closed as completed** 2023-08-06 22:39 UTC
Labels: bug
