### ISSUE TITLE
CURRENT ISSUE PLEASE READ: Cannot read properties of undefined

### ISSUE THREAD

**Issue by metalcupcake5** [SkyCryptWebsite/SkyCrypt#2092] opened 2023-11-23 06:07 UTC
If you've logged in since monday at 7:19 EST you may find that your profile is erroring with `Cannot read properties of undefined`
We believe the issue is primarily on Hypixel's side, Hypixel is rolling out a fix but at this time all we can do is wait.

Please do not make issues about this error in the meantime.

**Comment by AngelStar09** [comment] 2023-11-27 17:18
The error message for me says: "Cannot read properties of undefined (reading 'bronze')"
... what does bronze mean???

**Comment by Polygons1** [comment] 2023-11-29 08:00
have you tried https://hypixel.net/threads/public-api-endpoint-changes.5537323/ ?

**Comment by Polygons1** [comment] 2023-11-29 08:10
bruh, some of the Hypixel API endpoints are incorrect...

**Comment by hirohitonumberonefan** [comment] 2023-11-29 08:56
> bruh, some of the Hypixel API endpoints are incorrect...

they're aware but the api is legit broken

**Comment by Polygons1** [comment] 2023-11-29 09:35
> > bruh, some of the Hypixel API endpoints are incorrect...
> 
> they're aware but the api is legit broken

are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere

**Comment by Silewis37** [comment] 2023-11-30 00:01
> > bruh, some of the Hypixel API endpoints are incorrect...
> 
> 
> 
> they're aware but the api is legit broken

They arent broken at all, i fixed my local version of skycrypt and it all works with the updated endpoints. The issue is the endpoints and thats pretty much it.

**Comment by DuckySoLucky** [comment] 2023-11-30 19:21
> > > bruh, some of the Hypixel API endpoints are incorrect...
> > 
> > 
> > they're aware but the api is legit broken
> 
> are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere

status website is as useless as your dad's presence in your life.

**Comment by DuckySoLucky** [comment] 2023-11-30 19:22
> > > bruh, some of the Hypixel API endpoints are incorrect...
> > 
> > 
> > they're aware but the api is legit broken
> 
> They arent broken at all, i fixed my local version of skycrypt and it all works with the updated endpoints. The issue is the endpoints and thats pretty much it.

fix has been made around a week ago but the moment we start it in the production Hypixels' API chooses to die and hang up all sockets, I guess we're too much

**Comment by Silewis37** [comment] 2023-11-30 19:24
> > > > bruh, some of the Hypixel API endpoints are incorrect...
> 
> > > 
> 
> > > 
> 
> > > they're aware but the api is legit broken
> 
> > 
> 
> > They arent broken at all, i fixed my local version of skycrypt and it all works with the updated endpoints. The issue is the endpoints and thats pretty much it.
> 
> 
> 
> fix has been made around a week ago but the moment we start it in the production Hypixels' API chooses to die and hang up all sockets, I guess we're too much

Hypixels api cant handle skycrypt xD

**Comment by DuckySoLucky** [comment] 2023-11-30 19:25
> > > > > bruh, some of the Hypixel API endpoints are incorrect...
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > they're aware but the api is legit broken
> > 
> > 
> > > 
> > 
> > 
> > > They arent broken at all, i fixed my local version of skycrypt and it all works with the updated endpoints. The issue is the endpoints and thats pretty much it.
> > 
> > 
> > fix has been made around a week ago but the moment we start it in the production Hypixels' API chooses to die and hang up all sockets, I guess we're too much
> 
> Hypixels api cant handle skycrypt xD

pretty much, the moment we run prod on the latest branch it breaks

**Comment by Polygons1** [comment] 2023-12-01 09:45
> > > > bruh, some of the Hypixel API endpoints are incorrect...
> > > 
> > > 
> > > they're aware but the api is legit broken
> > 
> > 
> > are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere
> 
> status website is as useless as your dad's presence in your life.

What is blud waffling about 💀

**Comment by DuckySoLucky** [comment] 2023-12-02 15:07
> > > > > bruh, some of the Hypixel API endpoints are incorrect...
> > > > 
> > > > 
> > > > they're aware but the api is legit broken
> > > 
> > > 
> > > are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere
> > 
> > 
> > status website is as useless as your dad's presence in your life.
> 
> What is blud waffling about 💀

what are you waffling about u have no idea about what ur even talking so please don't talk pls ty ,3

**Comment by Polygons1** [comment] 2023-12-02 16:40
> > > > > > bruh, some of the Hypixel API endpoints are incorrect...
> > > > > 
> > > > > 
> > > > > they're aware but the api is legit broken
> > > > 
> > > > 
> > > > are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere
> > > 
> > > 
> > > status website is as useless as your dad's presence in your life.
> > 
> > 
> > What is blud waffling about 💀
> 
> what are you waffling about u have no idea about what ur even talking so please don't talk pls ty ,3

just go back to the hub

**Comment by DuckySoLucky** [comment] 2023-12-02 16:41
> > > > > > > bruh, some of the Hypixel API endpoints are incorrect...
> > > > > > 
> > > > > > 
> > > > > > they're aware but the api is legit broken
> > > > > 
> > > > > 
> > > > > are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere
> > > > 
> > > > 
> > > > status website is as useless as your dad's presence in your life.
> > > 
> > > 
> > > What is blud waffling about 💀
> > 
> > what are you waffling about u have no idea about what ur even talking so please don't talk pls ty ,3
> 
> just go back to the hub

bro I've been literally keeping SkyCrypt alive for the past year you're the one that should go to the hub 💀

**Comment by Polygons1** [comment] 2023-12-02 17:07
> > > > > > > > bruh, some of the Hypixel API endpoints are incorrect...
> > > > > > > 
> > > > > > > 
> > > > > > > they're aware but the api is legit broken
> > > > > > 
> > > > > > 
> > > > > > are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere
> > > > > 
> > > > > 
> > > > > status website is as useless as your dad's presence in your life.
> > > > 
> > > > 
> > > > What is blud waffling about 💀
> > > 
> > > 
> > > what are you waffling about u have no idea about what ur even talking so please don't talk pls ty ,3
> > 
> > 
> > just go back to the hub
> 
> bro I've been literally keeping SkyCrypt alive for the past year you're the one that should go to the hub 💀

you need to learn java for 20 years like me ☠️

**Comment by DuckySoLucky** [comment] 2023-12-02 17:11
> > > > > > > > > bruh, some of the Hypixel API endpoints are incorrect...
> > > > > > > > 
> > > > > > > > 
> > > > > > > > they're aware but the api is legit broken
> > > > > > > 
> > > > > > > 
> > > > > > > are you sure? the status website shows that the API is working and I don't see the new API changes in the code anywhere
> > > > > > 
> > > > > > 
> > > > > > status website is as useless as your dad's presence in your life.
> > > > > 
> > > > > 
> > > > > What is blud waffling about 💀
> > > > 
> > > > 
> > > > what are you waffling about u have no idea about what ur even talking so please don't talk pls ty ,3
> > > 
> > > 
> > > just go back to the hub
> > 
> > bro I've been literally keeping SkyCrypt alive for the past year you're the one that should go to the hub 💀
> 
> you need to learn java for 20 years like me ☠️ 

i can clearly tell from the way Ur profile looks and the way you type you ain't even 20 years old so please stop lying to people, pls Ty 💚

**Comment by preland** [comment] 2023-12-04 22:17
Most sane github issue

Question: does SkyCrypt currently require that _every_ api request returns properly? If not, I would be curious to see if the website would work better if it instead did 'per request' errors.

At least in my case, when I run into this issue, it seems like it snags on a particular request, which burns the entire lookup. And seeing how others are getting different "reading" values in the errors ('none', 'misc', 'bronze', 'journals') it definitely isn't a consistent bug.

In fact, the current failures could be the result of bandwidth limiting on Hypixel's end, perhaps even blocking specific api requests for certain usernames based on previous api requests for said user.

**Comment by DuckySoLucky** [comment] 2023-12-05 07:09
> Most sane github issue
> 
> Question: does SkyCrypt currently require that _every_ api request returns properly? If not, I would be curious to see if the website would work better if it instead did 'per request' errors.
> 
> At least in my case, when I run into this issue, it seems like it snags on a particular request, which burns the entire lookup. And seeing how others are getting different "reading" values in the errors ('none', 'misc', 'bronze', 'journals') it definitely isn't a consistent bug.
> 
> In fact, the current failures could be the result of bandwidth limiting on Hypixel's end, perhaps even blocking specific api requests for certain usernames based on previous api requests for said user.

99% of information is obtained from one endpoint (profiles). The result of current failures is hypxiel being dumb and breaking their API instead of holding promise and the moment we merge to V2 endpoint all of the sockets hang up cuz we are too much for hypixel. We can't really do anything other than to wait, you can temporarily use https://cupcake.shiiyu.moe/

**Comment by preland** [comment] 2023-12-05 14:44
Yeah, looking into it more, it seems like that is the case. No wonder Hypixel is having trouble with api requests: if someone tries to check how many chickens they’ve killed using the API, they get the whole farm 😂

I mean, how large is the JSON returned from a full request? Considering that it holds the metadata for all of the items in inventory, storage, ender chest, wardrobe, accessory bag etc. it must be absurd

Oh yeah and also the museum too I think…….

**Comment by DuckySoLucky** [comment] 2023-12-05 17:06
The response of some top players like DeathStreeks and Refraction is a few MBs so yeah.. kinda dogshit design ngl

**Comment by knlao** [comment] 2023-12-10 11:12
This has been 2 and a half week amd the pro lem is still not fixed :(
But 1 fun thing is that some players profile does not have the error, and others does. Why?

**Comment by DuckySoLucky** [comment] 2023-12-10 12:50
> This has been 2 and a half week amd the pro lem is still not fixed :( But 1 fun thing is that some players profile does not have the error, and others does. Why?

Fix has been made ages but the devs are busy and can't merge it so yeah.. The reason why it works for players and it does't is cuz Hypixel still hasn't merged all profiles

**Comment by knlao** [comment] 2023-12-11 02:56
> > This has been 2 and a half week amd the pro lem is still not fixed :( But 1 fun thing is that some players profile does not have the error, and others does. Why?
> 
> 
> 
> Fix has been made ages but the devs are busy and can't merge it so yeah.. The reason why it works for players and it does't is cuz Hypixel still hasn't merged all profiles

ok, thx

**Comment by knlao** [comment] 2023-12-16 12:20
Are you sure that there is no solution for this issue? I see that other skyblock stats checkers such as the  skyhelper bot in discord still work.

**Comment by DuckySoLucky** [comment] 2023-12-27 18:01
@metalcupcake5

**Closed as completed** 2023-12-27 22:52 UTC
