### ISSUE TITLE
Number 1 priority should be this

### ISSUE THREAD

**Issue by Artinator11** [SkyCryptWebsite/SkyCrypt#391] opened 2021-04-13 10:51 UTC
**Describe the bug**
Technoblade's Pig rank doesn't show the correct colour of +'s
Its meant to be light blue

**Profile/Location**
https://sky.shiiyu.moe/stats/Technoblade/Blueberry

**Expected behavior**
Correct colour +'s

**Screenshots**
![image](https://user-images.githubusercontent.com/71243393/114541292-ddcc1180-9c99-11eb-8e0d-27cde0e6a321.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Comment by nstringham** [comment] 2021-04-13 15:38
This was probably caused by #372

**Comment by nstringham** [comment] 2021-04-13 18:57
fixed by #394

**Closed** 2021-04-14 15:53 UTC
Labels: bug
