### ISSUE TITLE
Manifest shortcuts are broken

### ISSUE THREAD

**Issue by nstringham** [SkyCryptWebsite/SkyCrypt#1779] opened 2022-11-20 21:25 UTC
### Describe the bug
Manifest shortcuts are broken

### Steps to reproduce
1. favorite a profile
2. go to https://sky.shiiyu.moe/manifest.webmanifest

### Expect behavior
there should be a shortcuts to the favorited profile

### Actual behavior
the shortcuts list is empty

**Comment by MartinNemi03** [comment] 2022-11-20 21:31
This is (most likely) caused by NGINX cache. Needs to be fixed by making sure it's cache key also includes the favorite cookie.

**Comment by DuckySoLucky** [comment] 2023-08-07 16:41
@metalcupcake5

**Closed as completed** 2023-08-07 16:43 UTC
Labels: bug
