### ISSUE TITLE
experiment super pairs background is only 81px and not 100 like the rest

### ISSUE THREAD

**Issue by lochyj** [SkyCryptWebsite/SkyCrypt#929] opened 2021-11-03 09:14 UTC
The experiments super pairs background is only 81px and not 100px like the rest of the cards in the experiments

**Comment by dukio** [comment] 2021-11-03 09:35
I don't understand which background you are referring to, can you send a screenshot?

**Comment by lochyj** [comment] 2021-11-03 10:45
![image](https://user-images.githubusercontent.com/79903111/140046932-a1eefa17-d2c1-4f02-944b-42a01ceed111.png)

**Comment by dukio** [comment] 2021-11-07 13:27
@lochyj sorry but I keep on not understanding where the issue is... can you highlight it or explain better what the issue is?

**Comment by dukio** [comment] 2022-03-09 21:45
Closing since author didn't reply

**Closed by dukio** 2022-03-09 21:45 UTC
Labels: enhancement
