### ISSUE TITLE
Better text color contrast

### ISSUE THREAD

**Issue by noahhps** [SkyCryptWebsite/SkyCrypt#469] opened 2021-05-25 22:51 UTC
issue:
Certain text colors don't have enough contrast making text hard to read

fix:
darker colors for text in light mode

![Screenshot (117)](https://user-images.githubusercontent.com/62191281/119578239-03583a80-bd71-11eb-9e7f-4cc0eb5f2d48.png)
![Screenshot (118)](https://user-images.githubusercontent.com/62191281/119578242-04896780-bd71-11eb-9424-c837c7c861df.png)
![Screenshot (119)](https://user-images.githubusercontent.com/62191281/119578245-0521fe00-bd71-11eb-8e12-111563fff5f2.png)

**Comment by nstringham** [comment] 2021-06-24 19:37
Duplicate of #468

**Closed by nstringham** 2021-06-24 19:37 UTC
Labels: enhancement
