### ISSUE TITLE
Incorrect item texture

### ISSUE THREAD

**Issue by ronaldgameking** [SkyCryptWebsite/SkyCrypt#404] opened 2021-04-16 10:54 UTC
**Describe the bug**
A clear and concise description of what the bug is (e.g. My ender dragon's 2nd ability says 3.8% instead of 19%).
Textures for Necron armor (boots, leggings, chestplate) are incorrect and show the texures for wither armor for Hypixel Skyblock Pack (v13) texture pack.

**Profile/Location**
A link to the profile which the bug occurred with, if applicable (e.g. https://sky.shiiyu.moe/stats/Minikloon/Banana)
https://sky.shiiyu.moe/stats/ronaldgameking/Raspberry#Armor

**Additional Info**
If applicable, what pet/weapon/armor you are using and where you are in Skyblock.
Full Necron armor

**Expected behavior**
It should display the Necron armor texture

**Screenshots**
![image](https://user-images.githubusercontent.com/21692337/115014605-d9c70c00-9eb2-11eb-85c3-4c20f8b20a77.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 87.0

**Additional context**

**Comment by nstringham** [comment] 2021-04-16 17:18
> Thank you for bringing this issue to our attention. Expect a developer to comment within the first 2-3 hours of issue submission

We really need to change that I It's not a guarantee that a developer will be available within the first 2-3 hours More like the first 2-3 days

**Comment by nstringham** [comment] 2021-04-16 17:20
This seams like a duplicate of #256

**Comment by metalcupcake5** [comment] 2021-04-16 17:43
> > Thank you for bringing this issue to our attention. Expect a developer to comment within the first 2-3 hours of issue submission
> 
> We really need to change that I It's not a guarantee that a developer will be available within the first 2-3 hours More like the first 2-3 days

changed in 535844356cb19272299c7fe5cc18025a85e5bdc9

**Comment by Artinator11** [comment] 2021-04-17 08:04
> ~This seams like a duplicate of #256~
> 
> Edit: probably just related to #256

Daniel: #404

The Cooler Daniel: #256

**Comment by andreasflys** [comment] 2021-04-27 17:21
yep

**Closed** 2021-11-18 18:30 UTC
Labels: bug
